//created on: Jul 4, 2013
package com.dicks.rules

//list any import classes here.
import com.dicks.pojo.Orders
import com.dicks.pojo.Store
import com.dicks.pojo.Product

import com.dicks.engine.PackageE
import com.dicks.engine.PackageTestResult

import com.dicks.dao.InventoryDAO;

import java.util.ArrayList
import java.*;
import java.util.HashMap

//declare any global variables here
rule "Explode Cart"
    agenda-group "init"
    auto-focus true
    salience 10
    dialect "java"
    when
        $order : Orders()
        $item : Product() from $order.getProducts()
    then
        insert( $item );
//        modify ($order) { setExploredItem($order.getExploredItem() + 1); }
//        System.out.println("order quantity: " + $order.getQuantity());
//        System.out.println("exlored: " + $order.getExploredItem());
		
        drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "first" ).setFocus();
end

/*
rule "Explode Cart end"
    agenda-group "init"
    auto-focus true
    salience 8
    dialect "java"
    when
        $order : Order()
    then
        drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "first" ).setFocus();
end
*/

rule "filter stock"
	salience 10
	agenda-group "first"
    when    	
    	$item : Product()
    	$store : Store()
    	eval(!InventoryDAO.getInstance().containProduct($store, $item))
    then
        retract($store);
end

/*
rule "record stores"
	salience 10
	agenda-group "first"
    when    	
    	$order : Order()
		$store : Store()
    then
    	modify ($order) { addStore($store) }
        retract($store);
end
*/

rule  "special 1"
	salience 9
	agenda-group "first"
    when
    	//$store : Store(StoreID == 5);
       
//        $i : Product( ((weight > 10)|| ( size > 1))&& (( productID == 1 )|| (productID == 2 )|| (productID == 3 )))from $o.getProducts()
        $o : Orders()
        $i : Product(prodId == 5) 
        $store : Store(storeId == 5)
        eval(!InventoryDAO.getInstance().containProduct($store, $i))
        
        
    then     
    	System.out.println("special routes allocated");
    	PackageE p = new PackageE($o);
    	p.addProduct($i);
    	insert (p);  
    	p.setAllocated(true); 
        
        retract($i);
end


rule  "Mininum Packagethreshold0"
	salience 7
	agenda-group "first"
    when
        $o : Orders()
//        $i : Product( ((weight > 10)|| ( size > 1))&& (( productID == 1 )|| (productID == 2 )|| (productID == 3 )))from $o.getProducts()
        $i : Product(weight >= 10 && special == null)
        
    then     
    	PackageE p = new PackageE($o);
    	p.addProduct($i);
    	insert (p);    
        $i.minPackage();
        retract($i);
end

rule "insert package for remaining products"
	salience 5
	agenda-group "first"
	when
		$i : Product()
		$o : Orders()
		not PackageE(isForRemain())
	then
		PackageE p = new PackageE($o);
		p.setForRemain(true);
		insert (p);
		System.out.println("insert new package");
//		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "split" ).setFocus();
//		System.out.println("set to next group");
end

rule "wrap up remaining products"
	salience 3
	agenda-group "first"
	when
		$i : Product()
		$p : PackageE(isForRemain())
	then
		$p.addProduct($i);
		retract($i);
		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "split" ).setFocus();
end

/*
rule "set to next group"
	agenda-group "first"
	when
		not Product()
	then
		System.out.println("set to split");
//		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "split" ).setFocus();		
end


rule "add all packages"
	salience 10
//	agenda-group "split"
	when
		$p : Package()
		$order : Order()
	then
		$order.addPackage($p);
//		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "report" ).setFocus();
end


rule "for not splitable packages"
	salience 5
//	agenda-group "split"
	when
		$p : Package(getSplitNum() == getProducts().size())
//		$order : Order()
	then
		System.out.println("Unable to handle this package " + $p + ", handed to vendor");
//		System.out.println("handle this package " + $p);
//		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "report" ).setFocus();
end

rule "for splitable packages"
	salience 4
	agenda-group "split"
	when
		$p : Package(getSplitNum() < getProducts().size() && !isAllocated())
		$order : Order()
	then	
		ArrayList r = Split.getTestResult($p, $order);
		if (r !=  null || r.size() == 0) {
			modify ($p) { setAllocated(true) }
			System.out.println("Get result for " + $p);
		} else {
			modify ($p) { setSplitNum($p.getSplitNum() + 1) }
			System.out.println("cannot solve in split " + $p.getSplitNum());
		}
//		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "report" ).setFocus();
end*/

/*
rule "for not splitable packages"
	salience 4
	agenda-group "split"
	when
		$p : Package( getSplitNum() == getProducts().size())
	then
		System.out.println("Unable to handle this package " + $p);
end

rule "for splitable packages"
	salience 4
	agenda-group "split"
	when
		$p : Package()
	then
		
		modify ($p) { setSplitNum($p.getSplitNum() + 1) }
		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "report" ).setFocus();
end
*/

rule "summarize"   
//	agenda-group "report"
    when
        store : Store()
    then
        System.out.println(store.getStoreId());        
end

rule "summarizeProduct"  
//	agenda-group "report" 
    when
        p : Product()
    then
        System.out.println(p.getProdName());        
end

rule "summarizePackage"
//	agenda-group "report"   
    when
        $p : PackageE()
    then
        System.out.println($p);        
end
