//created on: Jul 4, 2013
package com.dicks.rules

//list any import classes here.
import com.dicks.pojo.Orders
import com.dicks.pojo.Store
import com.dicks.engine.PackageE
import com.dicks.engine.OrderE
import com.dicks.pojo.Product
import com.dicks.engine.PackageTestResult

import com.dicks.dao.InventoryDAO;
import com.dicks.dao.OrderDetailDAO;

import java.util.ArrayList
import java.util.Arrays;
import java.*;
import java.util.HashMap


//declare any global variables here
rule "Explode Cart"
    agenda-group "init"
    auto-focus true
    salience 100
    dialect "java"
    when
        $order : Orders()
        $item : Product() from OrderDetailDAO.getInstance().getProductsByOrder($order)
    then
        insert( $item );
//        System.out.println();
//        modify ($order) { setExploredItem($order.getExploredItem() + 1); }
//        System.out.println("order quantity: " + $order.getQuantity());
//        System.out.println("exlored: " + $item.getProductName());
        drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "first" ).setFocus();
end

/*
rule "Explode Cart end"
    agenda-group "init"
    auto-focus true
    salience 8
    dialect "java"
    when
        $order : Order()
    then
        drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "first" ).setFocus();
end
*/

rule "filter stock"
	salience 10
	agenda-group "first"
    when    	
    	$order : Orders()
    	$store : Store()
    	eval(!InventoryDAO.getInstance().containAnyProductOrder($store, $order))
    then
    	System.out.println("retract " + $store);
        retract($store);
end

rule "get products more than 1"
	salience 10
	agenda-group "first"
	when 
		$product : Product($id: prodId, sku.equals("1"))
		$orderE : OrderE()
		eval ($orderE.getProductQty($id) > 3)
	then
		System.out.println("product " + $product.getProdName() + " over 3!");
end	

/*
rule  "Special Route0"
    salience 15
    when
        $order : Orders()
        $orderE : OrderE()
        $product : Product($id: prodId, sku.equals("1"))
        eval ($orderE.getProductQty($id) >2)
        $s : Store( storeId == 1)
        eval(InventoryDAO.getInstance().checkProduct($s, $product, ">", $orderE.getProductQty($id)))
    then
        System.out.println("special routes for product "+$product.getProdName()+" with quantity "+$orderE.getProductQty($id)+" is successfully allocated");
        PackageE p = new PackageE($order);
        p.addProduct($product);
        insert (p);
        p.setAllocated(true); 
        retract($product);
end
	

/*
rule "record stores"
	salience 9
	agenda-group "first"
    when    	
    	$order : Order()
		$store : Store()
    then
    	modify ($order) { addStore($store) }
        retract($store);
end
*/

rule  "Mininum Packagethreshold0"
	salience 8
	agenda-group "first"
    when
        $o : Orders()
        $oE : OrderE()
//        $i : Product( ((weight > 10)|| ( size > 1))&& (( productID == 1 )|| (productID == 2 )|| (productID == 3 )))from $o.getProducts()
        $i : Product(weight > 2000)
    then     
    	PackageE p = new PackageE($o);
    	p.addProduct($i, $oE.getProductQty($i.getProdId()));
    	insert (p);    
        $i.minPackage();
        retract($i);
end

rule "insert package for remaining products"
	salience 5
	agenda-group "first"
	when
		$i : Product()
		$o : Orders()
		not PackageE(isForRemain())
	then
		PackageE p = new PackageE($o);
		p.setForRemain(true);
		insert (p);
		System.out.println("insert new package");
//		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "split" ).setFocus();
//		System.out.println("set to next group");
end

rule "wrap up remaining products"
	salience 3
	agenda-group "first"
	when
		$i : Product()
		$p : PackageE(isForRemain())
		$oE : OrderE()
	then
		$p.addProduct($i, $oE.getProductQty($i.getProdId()));
		retract($i);
		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "split" ).setFocus();
end

/*
rule "summarizePackage1"
	salience 100
//	agenda-group "split"  
    when
        $p : Package()
    then
        System.out.println("first: " + $p);        
end


rule "set to next group"
	agenda-group "first"
	when
		not Product()
	then
//		System.out.println("set to split");
		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "split" ).setFocus();		
end
*/
/*
rule "add all packages"
	salience 10
//	agenda-group "split"
	when
		$p : Package()
		$order : Order()
	then
		$order.addPackage($p);
//		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "report" ).setFocus();
end

*/
rule "summarizePackage1"
	salience 100
//	agenda-group "split"   
    when
        $p : Package()
    then
        System.out.println($p);        
end




/*
rule "for not splitable packages"
	salience 4
	agenda-group "split"
	when
		$p : Package( getSplitNum() == getProducts().size())
	then
		System.out.println("Unable to handle this package " + $p);
end

rule "for splitable packages"
	salience 4
	agenda-group "split"
	when
		$p : Package()
	then

		modify ($p) { setSplitNum($p.getSplitNum() + 1) }
		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "report" ).setFocus();
end


rule "summarize"   
//	agenda-group "report"
    when
        store : Store()
    then
        System.out.println(store.getZoneID());        
end

rule "summarizeProduct"  
//	agenda-group "report" 
    when
        p : Product()
    then
        System.out.println(p.getProductName());        
end

rule "summarizePackage"
//	agenda-group "report"   
    when
        $p : Package()
    then
        System.out.println($p);        
end
*/
