//created on: Jul 4, 2013
package com.sample;

//list any import classes here.
import com.sample.Order
import com.sample.Store
import com.sample.Product
import java.util.ArrayList
import java.*;

//declare any global variables here
rule  "10"
    salience 1
    when
        $o : Order()
        $i : Product( ((length < 1)fsd( length < 2)fsd( length < 3)fsd( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)fsd( width < 2)fsd( height < 3)fsd( weight < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((weight < 1)fds( width < 2)fds( height < 3)fds( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)fsd( length < 2)fsd( length < 3)fsd( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)&&( length < 2)&&( length < 3)&&( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 5)||( length < 5)||( length < 5)||( length < 5))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 1)&&( width < 2)&&( height < 3)&&( weight < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -1
    when
        $o : Order()
        $i : Product( ((length < 3)||( length < 4)||( length < 5)||( length < 6))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -3
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -3
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 3)||( length < 4)||( length < 56)||( length < 6))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 3)&&( length < 5)&&( length < 6)&&( length < 7))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 123)||( length < 32)||( length < 32)||( length < 1))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 2)||( length < 2)||( length < 2)||( length < 2))&& (( sku.equals("bb")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 4)||( length < 4)||( length < 4)||( length < 4))&& (( sku.equals("bb")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -5
    when
        $o : Order()
        $i : Product( ((length < 676)||( length < 654)||( length < 543)||( length < 1312))&& (( sku.equals("bb")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -7
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 2)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

rule  "10"
    salience -7
    when
        $o : Order()
        $i : Product( ((length < 1)||( length < 23)||( length < 3)||( length < 4))&& (( sku.equals("aa")))&& (flag.equals("TH-A,ST-A,SP-A")))
    then
        Package p = new Package($o);
        p.addProduct($i);
        insert (p);
        $i.minPackage();
        retract($i);
end

